version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  nodeapp:
    build: .
    container_name: nodeapp_container
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/employeeManagement?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo-data:
